# This workflow will install Python dependencies, run tests and lint with a
# variety of Python versions For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: test

on:
  push:
    branches: [ "main", "develop", "fixes"]
  pull_request:
    branches: [ "main"]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        cd ${GITHUB_WORKSPACE}/scripts && ./setup.sh
    - name: lint
      if: always()
      run: |
        cd ${GITHUB_WORKSPACE}/scripts && ./lint.sh
    - name: Run unit tests
      run: |
        cd ${GITHUB_WORKSPACE}/scripts && ./test.sh